version: "2"

services:

    client:
        stdin_open: true
        tty: true
        restart: always
        build: ./
        depends_on:
            - db
        links:
            - "db:redis_db"
        environment:
            - REDIS_HOST=redis_db
    db:
        image: redislabs/redisgraph:2.0-edge
        ports:
            - "6379:6379"
